### ISSUE TITLE
`TypeError  __init__() got an unexpected keyword argument 'find_links'` when running `medikit init`

### ISSUE THREAD

**Issue by sfermigier** [python-medikit/medikit#108]
When running `medikit init`, I get:

```
❯ medikit update
  ✚  Medikit v.0.7.3  ✚
INFO:0000:root: Updating abilian_hcms with git, make, python features
INFO:0000:root: > dispatch ⚡ medikit.on_start (ProjectEvent)
INFO:0000:root:   > dispatch ⚡ medikit.feature.python.on_generate (ProjectEvent)
INFO:0000:root:   < dispatched medikit.feature.python.on_generate
INFO:0000:root:   ∙ W? classifiers.txt (0 bytes)
INFO:0000:root:   ∙ W? README.rst (0 bytes)
INFO:0000:root:   ∙ W? MANIFEST.in (14 bytes)
INFO:0000:root:   ∙ W? abilian_hcms/__init__.py (1 bytes)
INFO:0000:root:   ∙ W? abilian_hcms/_version.py (22 bytes)
INFO:0000:root:   ∙ W! setup.py (1608 bytes)
INFO:0000:root:   > dispatch ⚡ medikit.feature.make.on_generate (MakefileEvent)
INFO:0000:root:   < dispatched medikit.feature.make.on_generate
INFO:0000:root:   ∙ W! Makefile (3274 bytes)
INFO:0000:root: < dispatched medikit.on_start
INFO:0000:root: > dispatch ⚡ medikit.on_end (ProjectEvent)
CRIT:0000:root: Uncaught exception (in thread 140736177365888).
│ Traceback (most recent call last):
│   File "/Users/fermigier/.local/bin/medikit", line 10, in <module>
│     sys.exit(main())
│   File "/Users/fermigier/.local/pipx/venvs/medikit/lib/python3.7/site-packages/medikit/__main__.py", line 60, in main
│     return handler(config_filename, **options)
│   File "/Users/fermigier/.local/pipx/venvs/medikit/lib/python3.7/site-packages/medikit/commands/update.py", line 73, in handle
│     dispatcher.dispatch(medikit.on_end, event)
│   File "/Users/fermigier/.local/pipx/venvs/medikit/lib/python3.7/site-packages/medikit/events.py", line 47, in dispatch
│     event = super(LoggingDispatcher, self).dispatch(event_id, event)
│   File "/Users/fermigier/.local/pipx/venvs/medikit/lib/python3.7/site-packages/whistle/dispatcher.py", line 27, in dispatch
│     self.do_dispatch(self.get_listeners(event_id), event)
│   File "/Users/fermigier/.local/pipx/venvs/medikit/lib/python3.7/site-packages/whistle/dispatcher.py", line 99, in do_dispatch
│     listener(event)
│   File "/Users/fermigier/.local/pipx/venvs/medikit/lib/python3.7/site-packages/medikit/feature/python.py", line 449, in on_end
│     repository = PyPIRepository(pip_options, session)
│   File "/Users/fermigier/.local/pipx/venvs/medikit/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 95, in __init__
│     self.finder = PackageFinder(**finder_kwargs)
╰ TypeError  __init__() got an unexpected keyword argument 'find_links'
```

**Comment by sei-nicolas** [comment]
Same error here, with python 3.5 (also while updating requirements and/or launching a release).

From what I can see, this is directly related to https://github.com/jazzband/pip-tools/issues/853

I tried using latest pip-tools (4.0 instead of ~3.0) => introduces other troubles.

Lazy working solution on my side is to use pip < 19.2, which can be enforced through medikit/globals.py
