### ISSUE TITLE
Release pipeline: when publishing to pypi, "bad marshal data (unknown type code)" error

### ISSUE THREAD

**Issue by hartym** [python-medikit/medikit#85]
Probably linked to releasing with multiple version targets. Works with 3.5/3.6 but complains with 3.7. Need bytecode cache clearing between versions and/or regeneration? Maybe it's just because py3.7 is not released yet?

```
Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    download_url='https://github.com/python-medikit/medikit/archive/{version}.tar.gz'.format(version=version),
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
```

**Comment by hartym** [comment]
This happens because py3.7 installed is not the latest, fixed by using latest py3.7 release.
